/**:
  check_collision:
    ros__parameters:
      global_footprint: "[[1.61, 0.5], [1.61, -0.5], [-0.5, -0.5], [-0.5, 0.5]]"

      # extended 1m further, for use in narrow driving, so that AMR can always exit the lane
      # add some cross for better checking, as we only check the polygon not the inner part
      local_footprint: "[[2.4, 0.53], [2.4, -0.53], [-0.35, -0.53], [-0.35, 0.53]]"

      # smaller than the AMR - as we use this to check if the bin is feasible to drive in, at all
      # also here, add some cross for better checking, as we only check the polygon not the inner part
      narrow_driving_footprint: "[[1.61, 0.1], [1.61, -0.1], [-0.3, -0.1], [-0.3, 0.1], [1.61, 0.15], [1.61, -0.15], [-0.3, -0.15], [-0.3, 0.15], [1.4, 0.05], [1.4, -0.05], [-0.2, -0.05], [-0.2, 0.05], [1.61, 0.2], [1.61, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
