/**:
  global_costmap:
    global_costmap:
      ros__parameters:
        footprint: "[[1.615, 0.5], [1.615, -0.5], [-0.35, -0.5], [-0.35, 0.5]]"


  local_costmap:
    local_costmap:
      ros__parameters:
        footprint: "[[1.615, 0.5], [1.615, -0.5], [-0.35, -0.5], [-0.35, 0.5]]"
