controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    tricycle_controller:
      type: tricycle_controller/TricycleController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["right_wheel_joint", "left_wheel_joint", "forks_lift_joint"]

tricycle_controller:
  ros__parameters:
    open_loop: true
    traction_joint_name: traction_joint
    steering_joint_name: steering_joint
    use_stamped_vel: false
    enable_odom_tf: false
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    odom_only_twist: true
    # traction:
    #   max_acceleration: 5.0
    #   max_deceleration: 8.0
    # steering:
    #   max_position: 1.57 # pi/2
    #   max_velocity: 1.0