rosbag_recorder:
  ros__parameters:
    topics: # Without leading slash (/) if it is to be prepended with namespace
      [
        "global_costmap/costmap",
        "global_plan",
        "local_costmap/costmap",
        "local_costmap/published_footprint",
        "local_costmap/voxel_grid",
        "obstacles_markers",
        "teb_markers",
        "teb_poses",
        "tf",
        "tf_static",
        "create_feasible_putdown_goal",
        "joint_states",
        "cmd_vel",
        "cmd_vel_smoothed",
        "tricycle_controller/cmd_ackermann",
        "speed_limit",
        "speed_limit_close_vehicle",
        "speed_limit_w2mo_path",
        "odometry/filtered",
        "load_sensor_status",
        "/clock",
        "/layout/custom_objects",
        "/layout/paths",
        "/layout/process_points",
        "/layout/racks",
        "/layout/stations",
        "/occupancy_grid",
        "/occupancy_grid_updates",
        "/rosout",
        "diagnostics",
        "bt_logs_publisher/behavior_tree_log",
        "realsense_right/color/image_raw",
        "realsense_left/color/image_raw",
        "rgb/image_raw",
      ]
    bags_dir: "/data/rosbags" # Without last slash (/). if changed also change /code/deep_cv/docker/rosbags
    max_duration: 400
    upload_enabled: True
    storage_format: mcap #https://github.com/ros2/rosbag2#storage-format-plugin-architecture
