analyzers:
  ros__parameters:
    Nav2:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Nav2
      contains: ["Nav2"]
    Battery:
      type: diagnostic_aggregator/GenericAnalyzer
      path: BatterySoc
      contains: ["battery_soc"]
    BarcodeCameras:
      type: diagnostic_aggregator/GenericAnalyzer
      path: BarcodeCamerasStatus
      contains: ["barcode_cameras_status"]
    KalmanFilter:
      type: "diagnostic_aggregator/AnalyzerGroup"
      path: KalmanFilter
      ekf_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: ekf_node_status
        contains: ["Filter diagnostic updater"]
      ekf_odom_topic:
        type: diagnostic_aggregator/GenericAnalyzer
        path: ekf_odom_topic_status
        contains: ["odometry/filtered topic status"]
